#!/usr/bin/env python

# copyright 2011-2012 Stefano Karapetsas <stefano@karapetsas.com>

# This file is part of AutoMate.
#
# AutoMate is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# AutoMate is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with AutoMate.  If not, see <http://www.gnu.org/licenses/>.

import argparse
import configobj
import cowbuilder
import functions
import os
import shutil
import sys

# check if user is root
functions.check_root()

# arguments
parser = argparse.ArgumentParser()
parser.add_argument("--create", action="store_true")
parser.add_argument("--create-pbuilder", action="store_true")
parser.add_argument("--instance", type=str, default="automate")
args = parser.parse_args()

automate_path = os.path.dirname(os.path.realpath(__file__))
instance_path = os.path.join(automate_path, "instances", args.instance)

if args.create:

    if not os.path.exists(instance_path):
        os.makedirs(instance_path)

        for folder in ["upload", "builds", "queue", "run"]:
            os.mkdir(os.path.join(instance_path, folder))
            
        os.makedirs(os.path.join(instance_path, "pbuilder", "base.cow"))
        
        shutil.copy("automate.conf.sample", os.path.join(instance_path, "automate.conf"))
        shutil.copy("pbuilderrc.sample", os.path.join(instance_path, "pbuilderrc"))
        
        os.system("chmod 777 -v -R %s/" % instance_path)

        print "\nInstance %s created"
        print "Edit automate.conf and pbuilderrc, then execute the command:"
        print "\t./automate-tool --create-pbuilder"

elif args.create_pbuilder:
    
    if not os.path.exists("/usr/bin/cowbuilder"):
        print "E: install cowbuilder package first!"
        sys.exit(1)
    
    config = configobj.ConfigObj(os.path.join(instance_path, "automate.conf"))
    pbuilderrc_file = os.path.join(instance_path, "pbuilderrc")
    
    for dist in config['dists']:
        for arch in config['archs']:
    
            cb = cowbuilder.CowBuilder(dist, arch, pbuilderrc_file, None, None)
            ret = cb.create()
    
